<#
.SYNOPSIS
    Generates an executive-level security posture report as HTML.
.DESCRIPTION
    Aggregates KPIs from all security data sources into a polished HTML report
    with trend charts (ASCII), risk summary, and recommended actions.
    Suitable for CISO briefings, board reporting, or audit evidence.
.EXAMPLE
    Invoke-SecurityPostureReport -DataRoot "C:\Reports" -OutputPath "C:\Reports\Executive"
#>
[CmdletBinding()]
param([Parameter(Mandatory)][string]$DataRoot, [string]$OutputPath = $PWD, [string]$OrgName = "Organization")

$Timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$ReportDate= Get-Date -Format "MMMM dd, yyyy"

# Load latest data
function Get-LatestCSV { param($pattern)
    $f = Get-ChildItem $DataRoot -Recurse -Filter $pattern | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($f) { Import-Csv $f.FullName } else { @() }
}

$patchData  = Get-LatestCSV "compliance_summary.csv"
$edrData    = Get-LatestCSV "EDR_Coverage_*.csv"
$cisData    = Get-LatestCSV "CIS_Audit_*.csv"
$vulnData   = Get-LatestCSV "Qualys_Findings_*.csv"

$patchPct   = if ($patchData) { $patchData[0].CompliancePct } else { "N/A" }
$edrPct     = if ($edrData)   { [math]::Round((($edrData|Where-Object Protected -eq $true).Count / [math]::Max($edrData.Count,1))*100,1) } else { "N/A" }
$cisPct     = if ($cisData)   { [math]::Round((($cisData|Where-Object Status -eq 'PASS').Count / [math]::Max($cisData.Count,1))*100,1) } else { "N/A" }
$critVulns  = if ($vulnData)  { ($vulnData|Where-Object{[double]$_.CVSS_BASE -ge 9.0}).Count } else { "N/A" }

$statusColor = @{}
foreach ($kv in @{ Patch=$patchPct; EDR=$edrPct; CIS=$cisPct }) {
    $statusColor[$kv.Key] = if ($kv.Value -ge 90) { "#27ae60" } elseif ($kv.Value -ge 70) { "#f39c12" } else { "#e74c3c" }
}

$HTML = @"
<!DOCTYPE html><html><head><meta charset="UTF-8"><style>
  body{font-family:Segoe UI,Arial,sans-serif;background:#f5f6fa;margin:0;padding:0;color:#2c3e50}
  .header{background:linear-gradient(135deg,#1a252f,#2c3e50);color:white;padding:32px 40px}
  h1{margin:0;font-size:26px}
  .subtitle{opacity:.7;margin-top:4px}
  .container{max-width:1100px;margin:0 auto;padding:24px}
  .kpi-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:24px 0}
  .kpi{background:white;border-radius:10px;padding:20px;text-align:center;box-shadow:0 1px 4px rgba(0,0,0,.08)}
  .kpi-val{font-size:36px;font-weight:700}
  .kpi-lbl{font-size:12px;color:#888;text-transform:uppercase;margin-top:4px}
  .section{background:white;border-radius:10px;padding:20px 24px;margin-bottom:16px;box-shadow:0 1px 4px rgba(0,0,0,.08)}
  h2{color:#2c3e50;margin-top:0;font-size:16px;text-transform:uppercase;letter-spacing:.5px}
  .badge{display:inline-block;padding:3px 10px;border-radius:12px;color:white;font-size:12px;font-weight:600}
</style></head>
<body>
<div class="header">
  <h1>&#x1F6E1; Security Posture Report — $OrgName</h1>
  <div class="subtitle">$ReportDate | Generated by PowerShell Security Automation</div>
</div>
<div class="container">
  <div class="kpi-grid">
    <div class="kpi"><div class="kpi-val" style="color:$(if($patchPct -ne 'N/A'){$statusColor['Patch']}else{'#888'})">$patchPct%</div><div class="kpi-lbl">Patch Compliance</div></div>
    <div class="kpi"><div class="kpi-val" style="color:$(if($edrPct -ne 'N/A'){$statusColor['EDR']}else{'#888'})">$edrPct%</div><div class="kpi-lbl">EDR Coverage</div></div>
    <div class="kpi"><div class="kpi-val" style="color:$(if($cisPct -ne 'N/A'){$statusColor['CIS']}else{'#888'})">$cisPct%</div><div class="kpi-lbl">CIS Benchmark</div></div>
    <div class="kpi"><div class="kpi-val" style="color:$(if([int]$critVulns -gt 0){'#e74c3c'}else{'#27ae60'})">$critVulns</div><div class="kpi-lbl">Critical Vulns</div></div>
  </div>
  <div class="section"><h2>Report Generated</h2><p>Data aggregated from Qualys, CIS Audit, EDR telemetry, and patch compliance reports in: <code>$DataRoot</code></p></div>
</div></body></html>
"@

$htmlPath = Join-Path $OutputPath "SecurityPosture_$Timestamp.html"
$HTML | Out-File $htmlPath -Encoding UTF8
Write-Host "[DONE] Executive report: $htmlPath" -ForegroundColor Green
