<#
.SYNOPSIS
    Generates and sends a daily/weekly security operations digest email.
.DESCRIPTION
    Aggregates data from multiple sources (Qualys, AD audit, patch compliance,
    EDR coverage) into a formatted HTML security digest for leadership or SOC team.
.PARAMETER Recipients
    Email address(es) for the digest.
.PARAMETER SMTPServer
    SMTP relay server.
.PARAMETER DataSources
    Hashtable of data source CSV paths to include in digest.
.EXAMPLE
    Send-SecurityDigest -Recipients "ciso@company.com","soc@company.com" `
        -SMTPServer "smtp.corp.local" -Subject "Weekly Security Digest"
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string[]]$Recipients,
    [Parameter(Mandatory)][string]$SMTPServer,
    [string]$From       = "security-automation@company.com",
    [string]$Subject    = "Security Operations Digest - $(Get-Date -Format 'yyyy-MM-dd')",
    [hashtable]$DataSources = @{},
    [string]$LogPath    = $PWD
)

function New-HtmlSection {
    param([string]$Title, [string]$Icon, $Data, [string]$StatusField)
    $rows = $Data | ForEach-Object {
        $rowColor = if ($StatusField -and $_.$StatusField -match "FAIL|Error|High|Critical") { "#fff3cd" } else { "white" }
        $cells = ($_.PSObject.Properties | ForEach-Object { "<td style='padding:4px 8px;border-bottom:1px solid #eee'>$($_.Value)</td>" }) -join ""
        "<tr style='background:$rowColor'>$cells</tr>"
    }
    $headers = ($Data[0].PSObject.Properties.Name | ForEach-Object { "<th style='padding:6px 8px;background:#2c3e50;color:white;text-align:left'>$_</th>" }) -join ""
    @"
    <div style="margin-bottom:24px">
        <h2 style="color:#2c3e50;border-bottom:2px solid #3498db;padding-bottom:6px">$Icon $Title</h2>
        <table style="border-collapse:collapse;width:100%;font-size:13px">
            <thead><tr>$headers</tr></thead>
            <tbody>$($rows -join '')</tbody>
        </table>
    </div>
"@
}

$ReportDate = Get-Date -Format "dddd, MMMM dd yyyy - HH:mm"
$Sections   = ""

foreach ($key in $DataSources.Keys) {
    if (Test-Path $DataSources[$key]) {
        $data = Import-Csv $DataSources[$key] | Select-Object -First 20
        if ($data) { $Sections += New-HtmlSection -Title $key -Icon "📊" -Data $data }
    }
}

$HTML = @"
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><style>
    body { font-family: Segoe UI, Arial, sans-serif; max-width:1200px; margin:0 auto; padding:20px; color:#333; }
    .header { background: linear-gradient(135deg, #1a252f, #2c3e50); color:white; padding:20px 24px; border-radius:8px; margin-bottom:24px; }
    .metric-bar { display:flex; gap:16px; margin-bottom:24px; }
    .metric { background:white; border:1px solid #ddd; border-radius:8px; padding:16px 20px; flex:1; text-align:center; }
    .metric-val { font-size:32px; font-weight:700; color:#2c3e50; }
    .metric-label { font-size:12px; color:#666; text-transform:uppercase; }
    .footer { color:#999; font-size:12px; margin-top:32px; border-top:1px solid #eee; padding-top:12px; }
</style></head>
<body>
<div class="header">
    <h1 style="margin:0;font-size:22px">🛡️ Security Operations Digest</h1>
    <p style="margin:4px 0 0;opacity:0.8">$ReportDate | Generated by PowerShell Security Automation</p>
</div>
$Sections
<div class="footer">
    This report was automatically generated. Do not reply to this email.
    Generated by: PowerShell Security Automation | $env:COMPUTERNAME
</div>
</body></html>
"@

$HtmlPath = Join-Path $LogPath "SecurityDigest_$(Get-Date -Format yyyyMMdd_HHmm).html"
$HTML | Out-File $HtmlPath -Encoding UTF8

Send-MailMessage -To $Recipients -From $From -Subject $Subject `
    -Body $HTML -BodyAsHtml -SmtpServer $SMTPServer -Encoding UTF8
Write-Host "[+] Security digest sent to: $($Recipients -join ', ')" -ForegroundColor Green
Write-Host "    HTML saved: $HtmlPath" -ForegroundColor Gray
